name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: install dependencies
        run: npm install
      - name: Deploy to azure app service
        uses: azure/webapps-deploy@v2
      with:
        app-name: integrationtest
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .




